### ISSUE TITLE
cant launch spms in windows due to libcurl, libmpv and libzmq-mt missing

### ISSUE THREAD

**Issue by anispwyn** [toasterofbread/spmp-server#3]
![explorer_pUVWIWBlVB](https://github.com/toasterofbread/spmp-server/assets/36318840/6d22c200-7db4-47c1-8148-c5377bed9e2a)

what did i do wrong? i followed the instruction in the docs and yet seems to be unable to launch, using latest artifact on both client and server

**Comment by sayaka-sh** [comment]
My bad, I meant to include those libraries with releases of the server but I completely forgot to. I've updated the v0.3.0 release, try that.

**Comment by anispwyn** [comment]
yup, works now, thanks :3
